# Generated by Django 5.2.8 on 2026-01-27 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0020_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalinspectionmeasurement',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='finalinspectionmeasurement',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='finalinspectionmeasurement',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='finalinspectionmeasurement',
            name='s4',
        ),
        migrations.RemoveField(
            model_name='finalinspectionmeasurement',
            name='s5',
        ),
        migrations.RemoveField(
            model_name='finalinspectionmeasurement',
            name='s6',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='s4',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='s5',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='s6',
        ),
        migrations.CreateModel(
            name='FinalInspectionMeasurementSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField(help_text='Sample number (1, 2, 3...)')),
                ('value', models.FloatField(blank=True, null=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='qc.finalinspectionmeasurement')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('measurement', 'index')},
            },
        ),
        migrations.CreateModel(
            name='MeasurementSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField(help_text='Sample number (1, 2, 3...)')),
                ('value', models.FloatField(blank=True, null=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='qc.measurement')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('measurement', 'index')},
            },
        ),
    ]
