# Generated by Django 5.2.8 on 2026-01-28 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0021_dynamic_samples'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(db_index=True, help_text='Purchase Order Number', max_length=255)),
                ('style_name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('season', models.CharField(blank=True, help_text='e.g., Fall 2026, Spring 2027', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_styles', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='styles', to='qc.customer')),
            ],
            options={
                'verbose_name': 'Style Master',
                'verbose_name_plural': 'Style Masters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Display name for the link', max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='qc.stylemaster')),
            ],
            options={
                'verbose_name': 'Style Link',
                'verbose_name_plural': 'Style Links',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='SampleComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_type', models.CharField(choices=[('Fit Sample', 'Fit Sample'), ('PP Sample', 'PP Sample'), ('Size Set', 'Size Set'), ('Top of Production', 'Top of Production')], max_length=50)),
                ('comments_general', models.TextField(blank=True, verbose_name='General Customer Feedback')),
                ('comments_fit', models.TextField(blank=True, verbose_name='Fit Comments')),
                ('comments_workmanship', models.TextField(blank=True, verbose_name='Workmanship Comments')),
                ('comments_wash', models.TextField(blank=True, verbose_name='Wash Comments')),
                ('comments_fabric', models.TextField(blank=True, verbose_name='Fabric Comments')),
                ('comments_accessories', models.TextField(blank=True, verbose_name='Accessories Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='qc.stylemaster')),
            ],
            options={
                'verbose_name': 'Sample Comment',
                'verbose_name_plural': 'Sample Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
