# Generated by Django 5.2.8 on 2026-01-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0022_style_cycle_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplecomment',
            options={'ordering': ['-sample_number', '-created_at'], 'verbose_name': 'Sample Comment', 'verbose_name_plural': 'Sample Comments'},
        ),
        migrations.AddField(
            model_name='samplecomment',
            name='sample_number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Sample'), (2, '2nd Sample'), (3, '3rd Sample'), (4, '4th Sample'), (5, '5th Sample')], default=1, help_text='Which submission number (1st, 2nd, etc.)'),
        ),
    ]
