# Generated by Django 5.2.8 on 2026-01-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0023_add_sample_number_to_samplecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecomment',
            name='sample_type',
            field=models.CharField(choices=[('Fit Sample', 'Fit Sample'), ('PP Sample', 'PP Sample'), ('Size Set', 'Size Set'), ('SMS', 'SMS'), ('Shipment Sample', 'Shipment Sample')], max_length=50),
        ),
    ]
