# Generated by Django 5.2.8 on 2026-02-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0024_update_sample_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='factory',
            field=models.CharField(blank=True, help_text='Factory name for analysis', max_length=255),
        ),
    ]
