# Generated by Django 5.2.8 on 2026-02-03 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0026_add_factory_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylemaster',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='styles', to='qc.factory'),
        ),
    ]
