# Generated by Django 5.2.8 on 2026-02-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0027_stylemaster_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='True if this inspection is a draft (incomplete, not finalized)'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
