# Generated by Django 5.2.8 on 2026-02-26 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0029_finalinspection_is_draft_finalinspection_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCommentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='sample_comment_images/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('general', 'General'), ('fit', 'Fit'), ('workmanship', 'Workmanship'), ('wash', 'Wash'), ('fabric', 'Fabric'), ('accessories', 'Accessories')], default='general', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='qc.samplecomment')),
            ],
            options={
                'verbose_name': 'Sample Comment Image',
                'verbose_name_plural': 'Sample Comment Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
