# Generated by Django 5.2.9 on 2026-02-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0030_samplecommentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecomment',
            name='accessories_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecomment',
            name='fabric_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecomment',
            name='fit_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecomment',
            name='general_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecomment',
            name='wash_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecomment',
            name='workmanship_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
