# Generated by Django 5.2.8 on 2026-04-23 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0032_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='specialized_remarks',
            field=models.TextField(blank=True, help_text='Non-standardizable, style-specific context for this feedback', verbose_name='Specialized Style Comments'),
        ),
        migrations.CreateModel(
            name='StandardizedDefect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Fabric', 'Fabric'), ('Workmanship', 'Workmanship'), ('Measurement', 'Measurement'), ('Wash/Finish', 'Wash/Finish'), ('Accessories/Trims', 'Accessories/Trims')], db_index=True, max_length=50)),
                ('defect_name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor')], default='Minor', max_length=10)),
            ],
            options={
                'verbose_name': 'Standardized Defect',
                'verbose_name_plural': 'Standardized Defects',
                'ordering': ['category', 'defect_name'],
                'unique_together': {('category', 'defect_name')},
            },
        ),
        migrations.CreateModel(
            name='InspectionCustomerIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_issues', to='qc.inspection')),
                ('standardized_defect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_issues', to='qc.standardizeddefect')),
            ],
            options={
                'verbose_name': 'Inspection Customer Issue',
                'verbose_name_plural': 'Inspection Customer Issues',
                'ordering': ['-created_at'],
            },
        ),
    ]
