# Generated by Django 5.2.8 on 2026-04-30 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0034_seed_standardized_defects'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='The first day of the month this rating applies to')),
                ('total_dev_samples', models.PositiveIntegerField(default=0, help_text='Total development samples submitted in this month')),
                ('total_dev_iterations', models.PositiveIntegerField(default=0, help_text='Sum of all sample numbers (iterations) for dev samples')),
                ('dev_iteration_ratio', models.FloatField(default=0.0, help_text='Average iterations per dev sample (total iterations / total samples)')),
                ('total_final_inspections', models.PositiveIntegerField(default=0, help_text='Total final inspections in this month')),
                ('first_pass_count', models.PositiveIntegerField(default=0, help_text='Count of final inspections passed on 1st attempt')),
                ('first_pass_yield', models.FloatField(default=0.0, help_text='Percentage of FPY (first_pass_count / total_final_inspections)')),
                ('internal_pass_rate', models.FloatField(default=0.0, help_text='Pass rate for internal QA evaluations')),
                ('customer_pass_rate', models.FloatField(default=0.0, help_text='Pass rate for customer evaluations')),
                ('base_score', models.FloatField(default=0.0, help_text='Average of internal and customer pass rates')),
                ('penalty_score', models.FloatField(default=0.0, help_text='Penalty deduction for high dev iterations and prod rework')),
                ('improvement_bonus', models.FloatField(default=0.0, help_text='Bonus for month-over-month improvement')),
                ('final_score', models.FloatField(default=0.0, help_text='Calculated final score before relative ranking')),
                ('percentile_rank', models.FloatField(default=0.0, help_text='Percentile rank amongst all factories for this month')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('N/A', 'N/A')], default='N/A', help_text='Relative grade based on percentile', max_length=3)),
                ('trend', models.CharField(choices=[('Up', 'Up'), ('Down', 'Down'), ('Stable', 'Stable')], default='Stable', help_text='Performance trend compared to previous month', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='qc.factory')),
            ],
            options={
                'ordering': ['-month', '-final_score'],
                'unique_together': {('factory', 'month')},
            },
        ),
    ]
