# Generated by Django 5.2.8 on 2026-04-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0035_factoryrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecomment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Resubmit', 'Resubmit')], default='Pending', max_length=20),
        ),
    ]
